version: '3.8'

services:
  db:
    image: postgres:16
    container_name: projec1-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./backend/main/resources/initdb:/docker-entrypoint-initdb.d